version: "2"
services:
    caddy:
        image: abiosoft/caddy:latest
        environment:
            - ACME_AGREE=true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/Caddyfile # to mount custom Caddyfile
networks:
    default:
        external:
            name: instance_default
